<a href="https://colab.research.google.com/github/igorivpp/code/blob/main/Campo_Minado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
def solver(A):
  counter = 0
  m = len(A) #numero de linas
  n = len(A[1][:]) # numero de colunas
  solution = ["?"]*(n-1)

  while counter < 10:
    for i in range(m):
      if np.all(A[i] == 0) == False:
        upperbound = 0
        lowerbound = 0
        for j in range(n-1):
          if A[i,j] < 0:
            lowerbound += A[i,j]
          elif A[i,j] >0:
            upperbound += A[i,j]
      
        if upperbound == A[i,-1]:
          #print("line", i, "meets upper bound")
          #solution = [0]*(n-1)
          for p in range(n-1):
            if A[i,p] > 0:
              solution[p] = 1
            elif A[i,p] < 0:
              solution[p] = 0
            #else:
            #  solution[p] = "?"
        elif lowerbound == A[i,-1]:
        #print("line", i, "meets lower bound")
          for k in range(n-1):
            if A[i,k] < 0:
              solution[k] = 1
            elif A[i,k] > 0:
              solution[k] = 0
            #else:
            #  solution[k] = "?"
        for i in range(n-1):
          
            if solution[i] == 0:
              for j in range(m):
                A[j][i] = 0
            elif solution[i] == 1:
              for j in range(m):
                A[j][-1] += -1*A[j][i]
                A[j][i] = 0
    counter +=1
    print(solution,counter)


    # for i in range(n-1):
    #   if solution[i] !=0 and solution[i] != 1:
    #     counter+=1
    # if counter == 10:
    #   running = False

        


In [ ]:
import numpy as np

def CMS(A):
  

def gauss(A):
    m = len(A) #numero de linas
    n = len(A[1][:]) # numero de colunas
    
####Esta sequencia troca as linhas para que o pivo sempre seja diferente de zero
    
    def absum(entries):           #esta função será útil mais tarde, ela pega um vetor e soma o valor absoluto das coordenadas
      return sum(abs(entries))        

    somas = []        #Armazena a soma de cada linha exceto da ultima coluna
    for i in range(m):
      somas.insert(i,-absum(A[i][0:n-1])) #A funcao argsort abaixo nao reordena por ordem decrescente entao coloquei o -absum.
    index = np.argsort(somas) #argsort cria um vetor com os indices apos o reordenamento.
    A=A[index]  #reodena as linas de acordo com o vetor index.


    for i in range(m-1):
      if A[i][i] == 0:
      for j in range(i+1,m):
        if A[j][i] != 0 and sum(abs(A[j])) == sum(abs(A[i])): #ou seja, a linha só é trocada se a linha encontrada tem a mesma soma de valores absolutos
          A[[j,i]] = A[[i,j]]
          break
    # for j in range(i,-1,-1):
    #   if A[j][i] != 0:
    #     A[[j,i]] = A[[i,j]]
    #     break

#Esta sequencia simplifica a matriz
    for i in range(m-1):
     for j in range(n):
      A[i][j] = A[i][j] + (-1)*A[i+1][j]
  ###################A partir daqui precisa de correção#################################  
    solution = solver(A)
    return solution

In [ ]:
###Testing
import numpy as np

def randbin(M,N,P):  
    return np.random.choice([0, 1], size=(M,N), p=[P, 1-P])

#A = randbin(3,4,0.4)
A = np.array(([1,1,0,0,0],[1,1,1,0,1],[0,1,1,1,1]))
print(A)
m = len(A) #numero de linas
n = len(A[1][:]) # numero de colunas


def absum(entries):
  return sum(abs(entries))

somas = []                            #Armazena a soma de cada linha exceto da ultima coluna
for i in range(m):
  somas.insert(i,-absum(A[i][0:n-1])) #A funcao argsort abaixo nao reordena por ordem decrescente entao coloquei o -absum.
index = np.argsort(somas)             #argsort cria um vetor com os indices apos o reordenamento.
A=A[index]                              #reodena as linas de acordo com o vetor index.
print(A)
for i in range(m-1):
  if A[i][i] == 0:
    for j in range(i+1,m):
      if A[j][i] != 0 and sum(abs(A[j])) == sum(abs(A[i])):
        A[[j,i]] = A[[i,j]]
        break
    # for j in range(i,-1,-1):
    #   if A[j][i] != 0:
    #     A[[j,i]] = A[[i,j]]
    #     break
print(A)

for i in range(m-1):
  for j in range(n):
    A[i][j] = A[i][j] + (-1)*A[i+1][j]
print(A)



[[1 1 0 0 0]
 [1 1 1 0 1]
 [0 1 1 1 1]]
[[1 1 1 0 1]
 [0 1 1 1 1]
 [1 1 0 0 0]]
[[1 1 1 0 1]
 [0 1 1 1 1]
 [1 1 0 0 0]]
[[ 1  0  0 -1  0]
 [-1  0  1  1  1]
 [ 1  1  0  0  0]]


In [ ]:
#Matrizes usadas no artigo, boas pra testar o codigo
import numpy as np

def solver(A):
  m = len(A) #numero de linas
  n = len(A[1][:]) # numero de colunas

  for i in range(m):
    arr = A[i,:n-1]
    copyarr = arr.copy()
    for j in range(len(copyarr)):
      if arr[j] > 0:
        copyarr[j] = 0
    if sum(copyarr) == A[i,-1]:
      print("line ", i ,"matches lowerbound")
      newarr = []
      for k in range(len(arr)):
        if arr[k] < 0:
          newarr.insert(k,0)
        else:
          newarr.insert(k,1)
      newarr.insert(len(newarr)+1,1)
    arr = A[i,:n-1]
    copyarr = arr.copy()
    for j in range(len(copyarr)):
      if arr[j] < 0:
        copyarr[j] = 0
    if sum(copyarr) == A[i,-1]:
      print("line ", i, " matches upper bound")
      newarr = [] 
      for k in range(len(arr)):
        if arr[k] > 0:
          newarr.insert(k,0)
        else:
          newarr.insert(k,1)
      newarr.insert(len(newarr)+1,1)
  return newarr
B = np.array(([1,1,0,0,0],[-1,1,1,1,-1],[1,-2,0,0,-1]))

solver(B)


line  0 matches lowerbound
line  1 matches lowerbound


[0, 1, 1, 1, 1]

In [17]:
import numpy as np

B = np.array(([1,1,0,0,0],[1,1,1,0,1],[0,1,1,1,1]))

solver(B)

[0, 0, 1, 0] 1
[0, 0, 1, 0] 2
[0, 0, 1, 0] 3
[0, 0, 1, 0] 4
[0, 0, 1, 0] 5
[0, 0, 1, 0] 6
[0, 0, 1, 0] 7
[0, 0, 1, 0] 8
[0, 0, 1, 0] 9
[0, 0, 1, 0] 10
